INSERT INTO public.people (id, name, birthday, country) VALUES (5530, 'James McAvoy', '1979-04-21', 'Port Glasgow, Scotland, UK');
INSERT INTO public.people (id, name, birthday, country) VALUES (83002, 'Jessica Chastain', '1977-03-24', 'Southern California, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (19278, 'Bill Hader', '1978-06-07', 'Tulsa, Oklahoma, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (5296, 'James Ransone', '1979-06-02', 'Baltimore, Maryland, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (223901, 'Jay Ryan', '1981-08-29', 'Auckland, New Zealand');
INSERT INTO public.people (id, name, birthday, country) VALUES (1237603, 'Isaiah Mustafa', '1974-02-11', 'Portland - Oregon - USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (1330888, 'Andy Bean', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (137905, 'Bill Skarsgård', '1990-08-09', 'Vällingby, Sweden');
INSERT INTO public.people (id, name, birthday, country) VALUES (143593, 'Xavier Dolan', '1989-03-20', 'Montréal, Québec, Canada');
INSERT INTO public.people (id, name, birthday, country) VALUES (129985, 'Teach Grant', '1973-01-25', 'Toronto, Ontario,  Canada');
INSERT INTO public.people (id, name, birthday, country) VALUES (1113116, 'Andy Muschietti', '1973-08-26', 'Buenos Aires, Argentina');
INSERT INTO public.people (id, name, birthday, country) VALUES (18918, 'Dwayne Johnson', '1972-05-02', 'Hayward, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (976, 'Jason Statham', '1967-07-26', 'Shirebrook, Derbyshire, England, UK');
INSERT INTO public.people (id, name, birthday, country) VALUES (17605, 'Idris Elba', '1972-09-06', 'Hackney, London, England, UK');
INSERT INTO public.people (id, name, birthday, country) VALUES (556356, 'Vanessa Kirby', '1988-04-18', 'Wimbledon, London, England, UK');
INSERT INTO public.people (id, name, birthday, country) VALUES (1222992, 'Eiza González', '1990-01-30', 'Mexico City, Mexico');
INSERT INTO public.people (id, name, birthday, country) VALUES (1665, 'Eddie Marsan', '1968-06-23', 'Stepney, East London, England');
INSERT INTO public.people (id, name, birthday, country) VALUES (183048, 'Stephanie Vogt', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1619648, 'David Mumeni', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (2152103, 'Axel Nu', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1752964, 'Lampros Kalfuntzos', '1980-07-19', 'Athens, Greece');
INSERT INTO public.people (id, name, birthday, country) VALUES (40684, 'David Leitch', '1969-12-31', 'Stratford, Texas, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (591998, 'Kathryn Bernardo', '1996-03-26', null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1128305, 'Alden Richards', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1887270, 'Maymay Entrata', '1997-05-06', 'Mambajao, Camiguin, Philippines');
INSERT INTO public.people (id, name, birthday, country) VALUES (1246880, 'Maricel Laxa', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (591023, 'Joross Gamboa', '1984-11-28', 'Daet, Camarines Norte, Philippines');
INSERT INTO public.people (id, name, birthday, country) VALUES (1708160, 'Jameson Blake', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1716307, 'Kakai Bautista', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (933413, 'Lito Pimentel', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1185025, 'Jeffrey Tam', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1928071, 'Lovely Abella', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (93106, 'Cathy Garcia-Molina', '1971-11-28', null);
INSERT INTO public.people (id, name, birthday, country) VALUES (17276, 'Gerard Butler', '1969-11-13', 'Paisley, Scotland, UK ');
INSERT INTO public.people (id, name, birthday, country) VALUES (192, 'Morgan Freeman', '1937-06-01', 'Memphis, Tennessee, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (9575, 'Jada Pinkett Smith', '1971-09-18', 'Baltimore, Maryland, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (129101, 'Lance Reddick', '1969-12-31', 'Baltimore, Maryland, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (1462, 'Tim Blake Nelson', '1964-05-11', 'Tulsa - Oklahoma - USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (15555, 'Piper Perabo', '1976-10-31', ' Dallas, Texas, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (1733, 'Nick Nolte', '1941-02-08', 'Omaha, Nebraska, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (6413, 'Danny Huston', '1962-05-14', 'Rome, Italy');
INSERT INTO public.people (id, name, birthday, country) VALUES (119893, 'Mark Arnold', '1957-05-23', 'Broomall, Pennsylvania, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (76543, 'Chris Browning', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (76422, 'Ric Roman Waugh', '1968-02-20', 'Los Angeles, California, Stati Uniti');
INSERT INTO public.people (id, name, birthday, country) VALUES (119589, 'Donald Glover', '1983-09-25', 'Stone Mountain, Georgia, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (14386, 'Beyoncé Knowles', '1981-09-04', 'Houston, Texas, United States');
INSERT INTO public.people (id, name, birthday, country) VALUES (15152, 'James Earl Jones', '1931-01-17', 'Arkabutla, Mississippi, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (5294, 'Chiwetel Ejiofor', '1977-07-10', 'Forest Gate, London, UK');
INSERT INTO public.people (id, name, birthday, country) VALUES (1981, 'Alfre Woodard', '1952-11-08', 'Tulsa, Oklahoma, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (84292, 'John Oliver', '1977-04-23', 'Birmingham - England - UK');
INSERT INTO public.people (id, name, birthday, country) VALUES (51878, 'John Kani', '1943-11-30', 'New Brighton, Port Elizabeth, Sudafrica');
INSERT INTO public.people (id, name, birthday, country) VALUES (19274, 'Seth Rogen', '1982-04-15', 'Vancouver, British Columbia, Canada');
INSERT INTO public.people (id, name, birthday, country) VALUES (973651, 'Billy Eichner', '1978-09-18', 'New York City, New York, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (934159, 'Eric André', '1983-04-04', 'Boca Raton, Florida, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (15277, 'Jon Favreau', '1966-10-19', 'Queens, New York, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (1277188, 'Jacob Tremblay', '2006-10-05', 'Vancouver, British Columbia, Canada');
INSERT INTO public.people (id, name, birthday, country) VALUES (2239159, 'Brady Noon', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (2177190, 'Keith L. Williams', '2007-05-21', 'Fort Worth, Texas, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (1782117, 'Molly Gordon', '1995-12-06', '  United States');
INSERT INTO public.people (id, name, birthday, country) VALUES (1984116, 'Midori Francis', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (62831, 'Will Forte', '1970-06-17', 'Alameda County, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (96529, 'Josh Caras', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (75318, 'Retta', null, 'Marietta Sirleaf, New Jersey');
INSERT INTO public.people (id, name, birthday, country) VALUES (1488961, 'LilRel Howery', '1979-12-17', '	Chicago, Illinois');
INSERT INTO public.people (id, name, birthday, country) VALUES (1274210, 'Millie Davis', '2007-06-18', 'Toronto, Ontario,  Canada');
INSERT INTO public.people (id, name, birthday, country) VALUES (84416, 'Gene Stupnitsky', '1977-08-26', null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1532, 'Bill Murray', '1950-09-21', 'Wilmette, Illinois, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (1023139, 'Adam Driver', '1983-11-19', 'San Diego, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (3063, 'Tilda Swinton', '1960-11-05', 'London, England, UK');
INSERT INTO public.people (id, name, birthday, country) VALUES (2838, 'Chloë Sevigny', '1974-11-18', 'Springfield, Massachusetts, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (77948, 'Selena Gomez', '1992-07-22', 'Grand Prairie, Texas, USA ');
INSERT INTO public.people (id, name, birthday, country) VALUES (2887, 'Tom Waits', '1949-12-07', 'Pomona, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (884, 'Steve Buscemi', '1957-12-13', 'New York City, New York, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (2047, 'Danny Glover', '1946-07-22', 'San Francisco, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (572541, 'Caleb Landry Jones', '1989-12-07', ' Garland, Texas, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (6403, 'Sara Driver', '1955-12-15', 'Westfield, New Jersey, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (4429, 'Jim Jarmusch', '1953-01-22', 'Akron, Ohio, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (1347525, 'Park Seo-joon', '1988-12-16', 'Seoul, South Korea');
INSERT INTO public.people (id, name, birthday, country) VALUES (17121, 'Ahn Sung-ki', '1952-01-01', 'Daegu, South Korea');
INSERT INTO public.people (id, name, birthday, country) VALUES (1845057, 'Woo Do-Hwan', '1992-07-12', null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1255881, 'Choi Woo-shik', '1990-03-26', 'Seoul, South Korea');
INSERT INTO public.people (id, name, birthday, country) VALUES (1988598, 'Park Ji-hyun', '1994-11-26', null);
INSERT INTO public.people (id, name, birthday, country) VALUES (2097275, 'Jung Ji-hoon', '2007-05-31', 'South Korea');
INSERT INTO public.people (id, name, birthday, country) VALUES (2391356, 'Lee Seung-hee', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1164503, 'Sim Hee-seop', '1986-02-26', null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1606060, 'Kim See-eun', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (2391351, 'Kim Seon-min', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1410322, 'Kim Joo-hwan', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1098962, 'Dove Cameron', '1996-01-15', ' Seattle, Washington, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (75041, 'Cameron Boyce', '1999-05-28', 'Los Angeles, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (1331457, 'Sofia Carson', '1993-04-10', null);
INSERT INTO public.people (id, name, birthday, country) VALUES (121868, 'Booboo Stewart', '1994-01-21', 'Beverly Hills, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (1421393, 'Mitchell Hope', '1994-06-27', '	Melbourne, Australia');
INSERT INTO public.people (id, name, birthday, country) VALUES (1729496, 'Thomas Doherty', '1995-04-21', 'Scozia, Regno Unito');
INSERT INTO public.people (id, name, birthday, country) VALUES (80613, 'China Anne McClain', '1998-08-25', 'Atlanta, Georgia, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (2056277, 'Aaron J Christopher', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (2362059, 'Kane Nelson', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (212828, 'Cheyenne Jackson', '1975-07-12', 'Newport - Washington - USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (65310, 'Kenny Ortega', '1950-04-18', 'Palo Alto, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (6193, 'Leonardo DiCaprio', '1974-11-11', 'Los Angeles, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (287, 'Brad Pitt', '1963-12-18', 'Shawnee, Oklahoma, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (234352, 'Margot Robbie', '1990-07-02', 'Gold Coast, Queensland, Australia ');
INSERT INTO public.people (id, name, birthday, country) VALUES (46593, 'Emile Hirsch', '1985-03-13', 'Topanga Canyon, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (1392137, 'Margaret Qualley', '1994-10-23', 'Montana, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (18082, 'Timothy Olyphant', '1968-05-20', 'Honolulu, Hawaii, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (1651362, 'Julia Butters', '2007-04-15', null);
INSERT INTO public.people (id, name, birthday, country) VALUES (86654, 'Austin Butler', '1991-08-17', 'Anaheim, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (501, 'Dakota Fanning', '1994-02-23', 'Conyers, Georgia, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (6905, 'Bruce Dern', '1936-06-04', 'Chicago, Illinois, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (138, 'Quentin Tarantino', '1963-03-27', 'Knoxville, Tennessee, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (10859, 'Ryan Reynolds', '1976-10-23', 'Vancouver, British Columbia, Canada');
INSERT INTO public.people (id, name, birthday, country) VALUES (1029934, 'Justice Smith', '1995-08-09', 'Los Angeles, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (221192, 'Kathryn Newton', '1997-02-08', 'Los Angeles, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (2440, 'Bill Nighy', '1949-12-12', 'Surrey, England, UK ');
INSERT INTO public.people (id, name, birthday, country) VALUES (3899, 'Ken Watanabe', '1959-10-21', 'Koide, Niigata, Japan');
INSERT INTO public.people (id, name, birthday, country) VALUES (62879, 'Chris Geere', '1981-03-18', 'Cambridge, Cambridgeshire, England, UK');
INSERT INTO public.people (id, name, birthday, country) VALUES (1325961, 'Suki Waterhouse', '1992-01-05', 'Hammersmith, London, England, UK');
INSERT INTO public.people (id, name, birthday, country) VALUES (174708, 'Josette Simon', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (2300244, 'Alejandro De Mesa', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1089873, 'Rita Ora', '1990-11-26', 'Pristina, Serbia, Yugoslavia');
INSERT INTO public.people (id, name, birthday, country) VALUES (65630, 'Rob Letterman', '1970-10-31', 'Honolulu, Hawaii, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (31, 'Tom Hanks', '1956-07-09', 'Concord, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (12898, 'Tim Allen', '1953-06-13', 'Denver, Colorado, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (8873, 'Annie Potts', '1952-10-28', 'Franklin, Kentucky, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (3234, 'Joan Cusack', '1962-10-11', 'New York City, New York, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (25147, 'Tony Hale', '1970-09-30', 'West Point, New York, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (6384, 'Keanu Reeves', '1964-09-02', 'Beirut, Lebanon');
INSERT INTO public.people (id, name, birthday, country) VALUES (298410, 'Keegan-Michael Key', '1971-03-22', 'Southfield - Michigan - USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (291263, 'Jordan Peele', '1979-02-21', 'New York City, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (110014, 'Christina Hendricks', '1975-05-03', 'Knoxville, Tennessee, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (209596, 'Ally Maki', '1986-01-01', 'Seattle, Washington, U.S.A');
INSERT INTO public.people (id, name, birthday, country) VALUES (84496, 'Josh Cooley', '1980-05-23', 'Los Angeles, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (10872, 'Patton Oswalt', '1969-01-27', 'Portsmouth, Virginia, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (156962, 'Eric Stonestreet', '1971-09-09', 'Kansas City, Kansas, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (55638, 'Kevin Hart', '1979-07-06', 'Philadelphia, Pennsylvania, USA ');
INSERT INTO public.people (id, name, birthday, country) VALUES (213001, 'Jenny Slate', '1982-03-25', 'Milton, Massachusetts, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (475512, 'Ellie Kemper', '1980-05-02', 'Kansas City, Missouri, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (25703, 'Lake Bell', '1979-03-24', 'New York City, New York, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (56159, 'Dana Carvey', '1955-06-02', 'Missoula, Montana, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (500427, 'Hannibal Buress', '1983-02-04', 'Chicago, Illinois, US');
INSERT INTO public.people (id, name, birthday, country) VALUES (452205, 'Bobby Moynihan', '1978-01-31', null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1230868, 'Tiffany Haddish', '1979-12-03', 'Los Angeles, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (124748, 'Chris Renaud', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1303037, 'Taron Egerton', '1989-11-10', 'Birkenhead, Merseyside, England, UK');
INSERT INTO public.people (id, name, birthday, country) VALUES (478, 'Jamie Bell', '1986-03-14', 'Billingham, Stockton on Tees, England, UK');
INSERT INTO public.people (id, name, birthday, country) VALUES (512991, 'Richard Madden', '1986-06-18', 'Elderslie, Renfrewshire, Scotland, UK');
INSERT INTO public.people (id, name, birthday, country) VALUES (18997, 'Bryce Dallas Howard', '1981-03-02', 'Los Angeles, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (9138, 'Gemma Jones', '1942-12-04', 'Marylebone, London, England, UK');
INSERT INTO public.people (id, name, birthday, country) VALUES (978, 'Steven Mackintosh', '1967-04-30', 'Cambridge, Cambridgeshire, England, UK');
INSERT INTO public.people (id, name, birthday, country) VALUES (126457, 'Tom Bennett', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (2316169, 'Matthew Illesley', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1538851, 'Kit Connor', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (142389, 'Charlie Rowe', '1996-04-23', 'Islington, London, England');
INSERT INTO public.people (id, name, birthday, country) VALUES (974, 'Dexter Fletcher', '1966-01-31', 'North London, England, UK');
INSERT INTO public.people (id, name, birthday, country) VALUES (1372369, 'Samara Weaving', '1992-02-23', 'Adelaide, Australia');
INSERT INTO public.people (id, name, birthday, country) VALUES (1533, 'Andie MacDowell', '1958-04-21', 'Gaffney, South Carolina, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (225411, 'Mark O''Brien', '1984-05-07', 'Canada ');
INSERT INTO public.people (id, name, birthday, country) VALUES (11702, 'Adam Brody', '1979-12-15', 'San Diego, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (15319, 'Henry Czerny', '1959-02-08', 'Toronto, Ontario, Canada');
INSERT INTO public.people (id, name, birthday, country) VALUES (5889, 'Nicky Guadagni', null, 'Montréal, Québec, Canada');
INSERT INTO public.people (id, name, birthday, country) VALUES (207491, 'Melanie Scrofano', null, 'Ottawa, Ontario, Canada');
INSERT INTO public.people (id, name, birthday, country) VALUES (1309774, 'Kristian Bruun', '1979-10-25', 'Toronto, Ontario, Canada');
INSERT INTO public.people (id, name, birthday, country) VALUES (199486, 'Elyse Levesque', '1985-09-10', 'Regina, Saskatchewan, Canada');
INSERT INTO public.people (id, name, birthday, country) VALUES (33343, 'John Ralston', '1964-10-09', 'Miramichi, New Brunswick, Canada');
INSERT INTO public.people (id, name, birthday, country) VALUES (66681, 'Matt Bettinelli-Olpin', '1978-02-19', 'California, - USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (35029, 'David Harbour', '1974-04-10', 'New York City, New York, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (63, 'Milla Jovovich', '1975-12-17', 'Kiev, Ukraine');
INSERT INTO public.people (id, name, birthday, country) VALUES (6972, 'Ian McShane', '1942-09-29', 'Blackburn, Lancashire, England, UK');
INSERT INTO public.people (id, name, birthday, country) VALUES (1535218, 'Sasha Lane', '1995-09-29', 'Houston, Texas, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (1115, 'Stephen Graham', '1973-08-03', 'Kirkby, Lancashire, England, UK');
INSERT INTO public.people (id, name, birthday, country) VALUES (18307, 'Daniel Dae Kim', '1968-08-04', 'Pusan, South Korea');
INSERT INTO public.people (id, name, birthday, country) VALUES (2598, 'Sophie Okonedo', '1969-01-01', 'London, England, UK');
INSERT INTO public.people (id, name, birthday, country) VALUES (56100, 'Alistair Petrie', '1970-09-30', null);
INSERT INTO public.people (id, name, birthday, country) VALUES (63364, 'Brian Gleeson', '1987-11-14', 'Dublin, Ireland');
INSERT INTO public.people (id, name, birthday, country) VALUES (1146114, 'Penelope Mitchell', '1991-07-24', 'Melbourne, Victoria, Australia');
INSERT INTO public.people (id, name, birthday, country) VALUES (57581, 'Neil Marshall', '1970-05-25', 'Newcastle upon Tyne - England - UK');
INSERT INTO public.people (id, name, birthday, country) VALUES (2364949, 'Melanie Martinez', '1995-04-28', 'Astoria, Queens, New York');
INSERT INTO public.people (id, name, birthday, country) VALUES (2364963, 'Elita Harkov', '1995-08-19', 'St. John''s, Newfoundland, Canada');
INSERT INTO public.people (id, name, birthday, country) VALUES (2364968, 'Megan Gage', null, 'San Francisco, California ');
INSERT INTO public.people (id, name, birthday, country) VALUES (2364967, 'Maggie Budzyna', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (2404918, 'Adrian Jurics', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (2404919, 'Gergely Kiss', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (2364961, 'Natalia Toth', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (2404920, 'Tamas Gog', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (2404921, 'Robert Szabolcs', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (2404922, 'Bence Balogh', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (9281, 'Elizabeth Banks', '1974-02-10', 'Pittsfield, Massachusetts, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (62562, 'David Denman', '1973-07-25', ' Newport Beach, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (2020904, 'Jackson A. Dunn', '2003-12-09', 'San Diego, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (191202, 'Matt Jones', '1981-11-01', 'Sacramento, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (449513, 'Meredith Hagner', '1987-05-31', null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1215392, 'Becky Wahlstrom', '1975-04-25', 'Chicago, Illinois, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (1683095, 'Emmie Hunter', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (37937, 'Gregory Alan Williams', '1956-06-12', 'Des Moines, Iowa, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (1832081, 'Annie Humphrey', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1569986, 'Abraham Clinkscales', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1362815, 'David Yarovesky', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1203378, 'Abimana Aryasatya', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (2135392, 'Muzakki Ramdhan', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (562217, 'Bront Palarae', '1978-09-27', 'Alor Setar, Kedah, Malaysia');
INSERT INTO public.people (id, name, birthday, country) VALUES (1154466, 'Tara Basro', '1990-06-11', 'Jakarta, Indonesia');
INSERT INTO public.people (id, name, birthday, country) VALUES (2367272, 'Fariz Fajar', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1028460, 'Rio Dewanto', '1987-08-28', null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1331143, 'Marissa Anita', '1983-03-29', 'Surabaya, Indonesia');
INSERT INTO public.people (id, name, birthday, country) VALUES (235425, 'Ario Bayu', '1985-02-06', 'Jakarta, Indonesia');
INSERT INTO public.people (id, name, birthday, country) VALUES (1206436, 'Lukman Sardi', '1971-07-14', 'Jakarta, Indonesia');
INSERT INTO public.people (id, name, birthday, country) VALUES (1185538, 'Pevita Pearce', '1992-10-06', 'Jakarta, Indonesia');
INSERT INTO public.people (id, name, birthday, country) VALUES (121798, 'Joko Anwar', '1976-01-03', 'Medan, Indonesia');
INSERT INTO public.people (id, name, birthday, country) VALUES (1428070, 'Isabela Moner', '2001-07-10', 'Cleveland, Ohio, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (11160, 'Danny Trejo', '1944-05-16', 'Los Angeles, California, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (1826682, 'Jeffrey Wahlberg', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1121, 'Benicio del Toro', '1967-02-19', 'San Germán, Puerto Rico');
INSERT INTO public.people (id, name, birthday, country) VALUES (239574, 'Eugenio Derbez', '1962-09-02', 'Mexico City - Distrito Federal - Mexico');
INSERT INTO public.people (id, name, birthday, country) VALUES (7242, 'Temuera Morrison', '1960-12-26', 'Rotorua, Île du Nord, Nouvelle-Zélande');
INSERT INTO public.people (id, name, birthday, country) VALUES (52605, 'Eva Longoria', '1975-03-15', 'Corpus Christi, Texas, USA');
INSERT INTO public.people (id, name, birthday, country) VALUES (454, 'Michael Peña', '1976-01-13', 'Chicago, Illinois, USA ');
INSERT INTO public.people (id, name, birthday, country) VALUES (1494865, 'Nicholas Coombe', null, null);
INSERT INTO public.people (id, name, birthday, country) VALUES (1109111, 'Madeleine Madden', null, 'Australia');
INSERT INTO public.people (id, name, birthday, country) VALUES (26205, 'James Bobin', null, null);